Import et traitement du dataset des evenements de Nantes

In [ ]:
import pandas as pd
from utils.cleaning_functions import create_date_debut, create_date_fin
from datetime import datetime

In [4]:
csv_link = '/Users/manu/Desktop/SUP/Semaine Campus/INPUT/244400404_agenda-evenements-nantes-nantes-metropole.csv'

In [5]:
df = pd.read_csv(csv_link, sep = ';')

# Exploration

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3198 entries, 0 to 3197
Data columns (total 54 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Identifiant                                      3198 non-null   int64
 1   Nom de l'événement                               3198 non-null   object
 2   Description                                      3191 non-null   object
 3   Festival                                         234 non-null    object
 4   Emetteur                                         3198 non-null   object
 5   Thème                                            3196 non-null   object
 6   Catégorie 1                                      3196 non-null   object
 7   Catégorie 2                                      631 non-null    object
 8   Catégorie 3                                      92 non-null     object
 9   Catégorie 4                                      35 non-null     object
 10  Catégorie 5                                      14 non-null     object
 11  Type de public attendu                           2564 non-null   object
 12  Pour enfants -12 ans                             3198 non-null   object
 13  Date                                             3198 non-null   object
 14  Heure de début                                   3132 non-null   object
 15  Heure de fin                                     2343 non-null   object
 16  Complet                                          3198 non-null   object
 17  Annulé                                           3198 non-null   object
 18  Reporté                                          3198 non-null   object
 19  Date report                                      0 non-null      float64
 20  Organisateurs                                    516 non-null    object
 21  Nom du lieu                                      2828 non-null   object
 22  Lieu : adresse                                   2892 non-null   object
 23  Lieu : ville                                     2892 non-null   object
 24  Lieu : code postal                               2892 non-null   float64
 25  Lieu : quartier                                  2672 non-null   object
 26  Lieu : site Web                                  2389 non-null   object
 27  Lieu : téléphone                                 2139 non-null   object
 28  Lieu : courriel                                  1599 non-null   object
 29  Gratuit                                          3198 non-null   object
 30  Précisions sur les tarifs                        2512 non-null   object
 31  Tarif social : carte blanche                     3198 non-null   object
 32  Informations supplémentaires                     9 non-null      object
 33  Accessibilité déficients auditifs                3198 non-null   object
 34  Accessibilité boucle magnétique                  3198 non-null   object
 35  Accessibilité déficients intellectuels           3198 non-null   object
 36  Accessibilité Langue des Signes Française (LSF)  3198 non-null   object
 37  Accessibilité déficients moteurs                 3198 non-null   object
 38  Accessibilité déficients psychiques              3198 non-null   object
 39  Accessibilité déficients visuels                 3198 non-null   object
 40  Lien  agenda                                     3198 non-null   object
 41  Latitude                                         2892 non-null   float64
 42  Longitude                                        2892 non-null   float64
 43  Géolocalisation                                  2892 non-null   object
 44  Type                                             3198 non-null   object
 45  Courriel                                         594 non-null    object
 46  Intitulé courriel                                594 non-null    object
 47  Intitulé lien Internet                           1466 non-null   object
 48  Intitulé contact                                 809 non-null    object
 49  Image                                            3191 non-null   object
 50  Téléphone contact                                809 non-null    object
 51  Lien Internet                                    1466 non-null   object
 52  Géolocalisation (latitude, longitude)            2892 non-null   object
 53  Géolocalisation (lieu)                           2890 non-null   object
dtypes: float64(4), int64(1), object(49)
memory usage: 1.3+ MB

In [7]:
df['Date'].nunique()

412

In [8]:
df.columns

Index(['Identifiant', 'Nom de l'événement', 'Description', 'Festival',
       'Emetteur', 'Thème', 'Catégorie 1', 'Catégorie 2', 'Catégorie 3',
       'Catégorie 4', 'Catégorie 5', 'Type de public attendu',
       'Pour enfants -12 ans', 'Date', 'Heure de début', 'Heure de fin',
       'Complet', 'Annulé', 'Reporté', 'Date report', 'Organisateurs',
       'Nom du lieu', 'Lieu : adresse', 'Lieu : ville', 'Lieu : code postal',
       'Lieu : quartier', 'Lieu : site Web', 'Lieu : téléphone',
       'Lieu : courriel', 'Gratuit', 'Précisions sur les tarifs',
       'Tarif social : carte blanche', 'Informations supplémentaires',
       'Accessibilité déficients auditifs', 'Accessibilité boucle magnétique',
       'Accessibilité déficients intellectuels',
       'Accessibilité Langue des Signes Française (LSF)',
       'Accessibilité déficients moteurs',
       'Accessibilité déficients psychiques',
       'Accessibilité déficients visuels', 'Lien  agenda', 'Latitude',
       'Longitude', 'Géolocalisation', 'Type', 'Courriel', 'Intitulé courriel',
       'Intitulé lien Internet', 'Intitulé contact', 'Image',
       'Téléphone contact', 'Lien Internet',
       'Géolocalisation (latitude, longitude)', 'Géolocalisation (lieu)'],
      dtype='object')

In [10]:
# Suppression des espaces insécables
df.columns = df.columns.str.replace('\xa0', ' ', regex=True).str.strip()

# Cleaning

In [11]:
df['Lieu : code postal'] = df['Lieu : code postal'].astype('str')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3198 entries, 0 to 3197
Data columns (total 54 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Identifiant                                      3198 non-null   int64
 1   Nom de l'événement                               3198 non-null   object
 2   Description                                      3191 non-null   object
 3   Festival                                         234 non-null    object
 4   Emetteur                                         3198 non-null   object
 5   Thème                                            3196 non-null   object
 6   Catégorie 1                                      3196 non-null   object
 7   Catégorie 2                                      631 non-null    object
 8   Catégorie 3                                      92 non-null     object
 9   Catégorie 4                                      35 non-null     object
 10  Catégorie 5                                      14 non-null     object
 11  Type de public attendu                           2564 non-null   object
 12  Pour enfants -12 ans                             3198 non-null   object
 13  Date                                             3198 non-null   object
 14  Heure de début                                   3132 non-null   object
 15  Heure de fin                                     2343 non-null   object
 16  Complet                                          3198 non-null   object
 17  Annulé                                           3198 non-null   object
 18  Reporté                                          3198 non-null   object
 19  Date report                                      0 non-null      float64
 20  Organisateurs                                    516 non-null    object
 21  Nom du lieu                                      2828 non-null   object
 22  Lieu : adresse                                   2892 non-null   object
 23  Lieu : ville                                     2892 non-null   object
 24  Lieu : code postal                               3198 non-null   object
 25  Lieu : quartier                                  2672 non-null   object
 26  Lieu : site Web                                  2389 non-null   object
 27  Lieu : téléphone                                 2139 non-null   object
 28  Lieu : courriel                                  1599 non-null   object
 29  Gratuit                                          3198 non-null   object
 30  Précisions sur les tarifs                        2512 non-null   object
 31  Tarif social : carte blanche                     3198 non-null   object
 32  Informations supplémentaires                     9 non-null      object
 33  Accessibilité déficients auditifs                3198 non-null   object
 34  Accessibilité boucle magnétique                  3198 non-null   object
 35  Accessibilité déficients intellectuels           3198 non-null   object
 36  Accessibilité Langue des Signes Française (LSF)  3198 non-null   object
 37  Accessibilité déficients moteurs                 3198 non-null   object
 38  Accessibilité déficients psychiques              3198 non-null   object
 39  Accessibilité déficients visuels                 3198 non-null   object
 40  Lien  agenda                                     3198 non-null   object
 41  Latitude                                         2892 non-null   float64
 42  Longitude                                        2892 non-null   float64
 43  Géolocalisation                                  2892 non-null   object
 44  Type                                             3198 non-null   object
 45  Courriel                                         594 non-null    object
 46  Intitulé courriel                                594 non-null    object
 47  Intitulé lien Internet                           1466 non-null   object
 48  Intitulé contact                                 809 non-null    object
 49  Image                                            3191 non-null   object
 50  Téléphone contact                                809 non-null    object
 51  Lien Internet                                    1466 non-null   object
 52  Géolocalisation (latitude, longitude)            2892 non-null   object
 53  Géolocalisation (lieu)                           2890 non-null   object
dtypes: float64(3), int64(1), object(50)
memory usage: 1.3+ MB

In [13]:
df['Lieu : code postal'] = df['Lieu : code postal'].str.replace('.0', '')

In [14]:
colums_to_keep = ['Identifiant', 'Date', 'Date','Heure de début','Nom du lieu','Lieu : adresse', 'Lieu : ville', 'Lieu : code postal',"Nom de l'événement", 'Lien Internet', 'Thème','Catégorie 1',	'Catégorie 2',	'Catégorie 3',	'Catégorie 4','Gratuit','Description', 'Image', 'Précisions sur les tarifs']

In [15]:
df = df[colums_to_keep]

In [16]:
df.head()

,Identifiant,Date,Date,Heure de début,Nom du lieu,Lieu : adresse,Lieu : ville,Lieu : code postal,Nom de l'événement,Lien Internet,Thème,Catégorie 1,Catégorie 2,Catégorie 3,Catégorie 4,Gratuit,Description,Image,Précisions sur les tarifs
0,65115,2025-02-19,2025-02-19,14:30,Théâtre 100 Noms,21 Quai des Antilles - Hangar à Bananes,Nantes,44200,Le Bossu de Notre-Dame - par le Théâtre 100 Noms,https://theatre100noms.com/,Culture,Concert - Musique,Théâtre - Humour,NaN,NaN,non,Création Théâtre 100 NomsUn spectacle enchante...,https://metropole.nantes.fr//banque/public/ima...,15 € à 22 € RÉSERVATIONS :- theatre100noms.co...
1,65184,2025-03-01,2025-03-01,20:30,Théâtre de Jeanne,5 Rue des Salorges,Nantes,44100,Amants à mi-temps,https://www.theatre-jeanne.com,Culture,Théâtre - Humour,NaN,NaN,NaN,non,Comédie de Léo Pasani. Un spectacle 100 % hum...,https://metropole.nantes.fr//banque/public/ima...,22 € / 14 € € (tarif réduit pour les étudiants...
2,65192,2025-03-12,2025-03-12,20:30,Théâtre de Jeanne,5 Rue des Salorges,Nantes,44100,"Récital Barbara, piano/voix - par Mélanie Le C...",https://www.theatre-jeanne.com,Culture,Concert - Musique,NaN,NaN,NaN,non,Concert/Spectacle musical interprété par Mélan...,https://metropole.nantes.fr//banque/public/ima...,22 € / 14 € € (tarif réduit pour les étudiants...
3,65194,2025-03-28,2025-03-28,20:30,Théâtre de Jeanne,5 Rue des Salorges,Nantes,44100,Vacances obligatoires,https://www.theatre-jeanne.com,Culture,Théâtre - Humour,NaN,NaN,NaN,non,Comédie écrite et mise en scène par Bruno Bach...,https://metropole.nantes.fr//banque/public/ima...,22 € / 14 € € (tarif réduit pour les étudiants...
4,65194,2025-03-20,2025-03-20,20:30,Théâtre de Jeanne,5 Rue des Salorges,Nantes,44100,Vacances obligatoires,https://www.theatre-jeanne.com,Culture,Théâtre - Humour,NaN,NaN,NaN,non,Comédie écrite et mise en scène par Bruno Bach...,https://metropole.nantes.fr//banque/public/ima...,22 € / 14 € € (tarif réduit pour les étudiants...

In [17]:
df['adresse'] = df['Lieu : adresse'] + ' ' + df['Lieu : code postal'] + ' ' + df['Lieu : ville']

In [18]:
df.drop(columns=['Lieu : adresse', 'Lieu : ville', 'Lieu : code postal'], inplace = True)

In [19]:
df.head()

,Identifiant,Date,Date,Heure de début,Nom du lieu,Nom de l'événement,Lien Internet,Thème,Catégorie 1,Catégorie 2,Catégorie 3,Catégorie 4,Gratuit,Description,Image,Précisions sur les tarifs,adresse
0,65115,2025-02-19,2025-02-19,14:30,Théâtre 100 Noms,Le Bossu de Notre-Dame - par le Théâtre 100 Noms,https://theatre100noms.com/,Culture,Concert - Musique,Théâtre - Humour,NaN,NaN,non,Création Théâtre 100 NomsUn spectacle enchante...,https://metropole.nantes.fr//banque/public/ima...,15 € à 22 € RÉSERVATIONS :- theatre100noms.co...,21 Quai des Antilles - Hangar à Bananes 44200 ...
1,65184,2025-03-01,2025-03-01,20:30,Théâtre de Jeanne,Amants à mi-temps,https://www.theatre-jeanne.com,Culture,Théâtre - Humour,NaN,NaN,NaN,non,Comédie de Léo Pasani. Un spectacle 100 % hum...,https://metropole.nantes.fr//banque/public/ima...,22 € / 14 € € (tarif réduit pour les étudiants...,5 Rue des Salorges 44100 Nantes
2,65192,2025-03-12,2025-03-12,20:30,Théâtre de Jeanne,"Récital Barbara, piano/voix - par Mélanie Le C...",https://www.theatre-jeanne.com,Culture,Concert - Musique,NaN,NaN,NaN,non,Concert/Spectacle musical interprété par Mélan...,https://metropole.nantes.fr//banque/public/ima...,22 € / 14 € € (tarif réduit pour les étudiants...,5 Rue des Salorges 44100 Nantes
3,65194,2025-03-28,2025-03-28,20:30,Théâtre de Jeanne,Vacances obligatoires,https://www.theatre-jeanne.com,Culture,Théâtre - Humour,NaN,NaN,NaN,non,Comédie écrite et mise en scène par Bruno Bach...,https://metropole.nantes.fr//banque/public/ima...,22 € / 14 € € (tarif réduit pour les étudiants...,5 Rue des Salorges 44100 Nantes
4,65194,2025-03-20,2025-03-20,20:30,Théâtre de Jeanne,Vacances obligatoires,https://www.theatre-jeanne.com,Culture,Théâtre - Humour,NaN,NaN,NaN,non,Comédie écrite et mise en scène par Bruno Bach...,https://metropole.nantes.fr//banque/public/ima...,22 € / 14 € € (tarif réduit pour les étudiants...,5 Rue des Salorges 44100 Nantes

In [20]:
df['price'] = df['Gratuit'].apply(lambda x : 'GRATUIT' if x == 'oui' else 'PAYANT')

In [21]:
df.head(2)

,Identifiant,Date,Date,Heure de début,Nom du lieu,Nom de l'événement,Lien Internet,Thème,Catégorie 1,Catégorie 2,Catégorie 3,Catégorie 4,Gratuit,Description,Image,Précisions sur les tarifs,adresse,price
0,65115,2025-02-19,2025-02-19,14:30,Théâtre 100 Noms,Le Bossu de Notre-Dame - par le Théâtre 100 Noms,https://theatre100noms.com/,Culture,Concert - Musique,Théâtre - Humour,NaN,NaN,non,Création Théâtre 100 NomsUn spectacle enchante...,https://metropole.nantes.fr//banque/public/ima...,15 € à 22 € RÉSERVATIONS :- theatre100noms.co...,21 Quai des Antilles - Hangar à Bananes 44200 ...,PAYANT
1,65184,2025-03-01,2025-03-01,20:30,Théâtre de Jeanne,Amants à mi-temps,https://www.theatre-jeanne.com,Culture,Théâtre - Humour,NaN,NaN,NaN,non,Comédie de Léo Pasani. Un spectacle 100 % hum...,https://metropole.nantes.fr//banque/public/ima...,22 € / 14 € € (tarif réduit pour les étudiants...,5 Rue des Salorges 44100 Nantes,PAYANT

In [22]:
df.drop(columns=['Gratuit', 'Précisions sur les tarifs'], inplace=True)

In [23]:
df.head(1)

,Identifiant,Date,Date,Heure de début,Nom du lieu,Nom de l'événement,Lien Internet,Thème,Catégorie 1,Catégorie 2,Catégorie 3,Catégorie 4,Description,Image,adresse,price
0,65115,2025-02-19,2025-02-19,14:30,Théâtre 100 Noms,Le Bossu de Notre-Dame - par le Théâtre 100 Noms,https://theatre100noms.com/,Culture,Concert - Musique,Théâtre - Humour,NaN,NaN,Création Théâtre 100 NomsUn spectacle enchante...,https://metropole.nantes.fr//banque/public/ima...,21 Quai des Antilles - Hangar à Bananes 44200 ...,PAYANT

In [24]:
cols_to_concat = ['Thème', 'Catégorie 1', 'Catégorie 2', 'Catégorie 3', 'Catégorie 4']

df['tags'] = df[cols_to_concat].apply(
    lambda row: ', '.join(row.dropna().astype(str).map(str.strip)),
    axis=1
)

In [25]:
df.head(1)

,Identifiant,Date,Date,Heure de début,Nom du lieu,Nom de l'événement,Lien Internet,Thème,Catégorie 1,Catégorie 2,Catégorie 3,Catégorie 4,Description,Image,adresse,price,tags
0,65115,2025-02-19,2025-02-19,14:30,Théâtre 100 Noms,Le Bossu de Notre-Dame - par le Théâtre 100 Noms,https://theatre100noms.com/,Culture,Concert - Musique,Théâtre - Humour,NaN,NaN,Création Théâtre 100 NomsUn spectacle enchante...,https://metropole.nantes.fr//banque/public/ima...,21 Quai des Antilles - Hangar à Bananes 44200 ...,PAYANT,"Culture, Concert - Musique, Théâtre - Humour"

In [26]:
df.drop(columns=cols_to_concat, inplace = True)

In [27]:
df.head(2)

,Identifiant,Date,Date,Heure de début,Nom du lieu,Nom de l'événement,Lien Internet,Description,Image,adresse,price,tags
0,65115,2025-02-19,2025-02-19,14:30,Théâtre 100 Noms,Le Bossu de Notre-Dame - par le Théâtre 100 Noms,https://theatre100noms.com/,Création Théâtre 100 NomsUn spectacle enchante...,https://metropole.nantes.fr//banque/public/ima...,21 Quai des Antilles - Hangar à Bananes 44200 ...,PAYANT,"Culture, Concert - Musique, Théâtre - Humour"
1,65184,2025-03-01,2025-03-01,20:30,Théâtre de Jeanne,Amants à mi-temps,https://www.theatre-jeanne.com,Comédie de Léo Pasani. Un spectacle 100 % hum...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Théâtre - Humour"

In [28]:
df.drop_duplicates(inplace=True)

In [29]:
df.dropna(how = 'all',inplace=True)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3198 entries, 0 to 3197
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Identifiant         3198 non-null   int64
 1   Date                3198 non-null   object
 2   Date                3198 non-null   object
 3   Heure de début      3132 non-null   object
 4   Nom du lieu         2828 non-null   object
 5   Nom de l'événement  3198 non-null   object
 6   Lien Internet       1466 non-null   object
 7   Description         3191 non-null   object
 8   Image               3191 non-null   object
 9   adresse             2892 non-null   object
 10  price               3198 non-null   object
 11  tags                3198 non-null   object
dtypes: int64(1), object(11)
memory usage: 299.9+ KB

In [31]:
df.columns.values[1] = 'DateDebut'  
df.columns.values[2] = 'DateFin'

In [32]:
df.rename(columns = {
    'Identifiant' : 'id',
    'Nom du lieu' : 'Lieu',
    'adresse' : 'Adresse',
    'tags' : 'Tags',
    'price' : 'Tarif',
    "Nom de l'événement" : 'Nom'
},inplace=True)

In [33]:
df.head(1)

,id,DateDebut,DateFin,Heure de début,Lieu,Nom,Lien Internet,Description,Image,Adresse,Tarif,Tags
0,65115,2025-02-19,2025-02-19,14:30,Théâtre 100 Noms,Le Bossu de Notre-Dame - par le Théâtre 100 Noms,https://theatre100noms.com/,Création Théâtre 100 NomsUn spectacle enchante...,https://metropole.nantes.fr//banque/public/ima...,21 Quai des Antilles - Hangar à Bananes 44200 ...,PAYANT,"Culture, Concert - Musique, Théâtre - Humour"

In [ ]:
# Nettoyage des colonnes (supprimer espaces et standardiser les NaN)
df['Heure de début'] = df['Heure de début'].astype(str).str.strip().replace('nan', None)

In [35]:
df['DateDebut'] = df.apply(create_date_debut, axis=1)
df['DateFin'] = df.apply(create_date_fin, axis=1)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3198 entries, 0 to 3197
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              3198 non-null   int64
 1   DateDebut       3198 non-null   datetime64[ns]
 2   DateFin         3198 non-null   datetime64[ns]
 3   Heure de début  3132 non-null   object
 4   Lieu            2828 non-null   object
 5   Nom             3198 non-null   object
 6   Lien Internet   1466 non-null   object
 7   Description     3191 non-null   object
 8   Image           3191 non-null   object
 9   Adresse         2892 non-null   object
 10  Tarif           3198 non-null   object
 11  Tags            3198 non-null   object
dtypes: datetime64[ns](2), int64(1), object(9)
memory usage: 299.9+ KB

In [37]:
df.head(5)

,id,DateDebut,DateFin,Heure de début,Lieu,Nom,Lien Internet,Description,Image,Adresse,Tarif,Tags
0,65115,2025-02-19 14:30:00,2025-02-19 23:59:59,14:30,Théâtre 100 Noms,Le Bossu de Notre-Dame - par le Théâtre 100 Noms,https://theatre100noms.com/,Création Théâtre 100 NomsUn spectacle enchante...,https://metropole.nantes.fr//banque/public/ima...,21 Quai des Antilles - Hangar à Bananes 44200 ...,PAYANT,"Culture, Concert - Musique, Théâtre - Humour"
1,65184,2025-03-01 20:30:00,2025-03-01 23:59:59,20:30,Théâtre de Jeanne,Amants à mi-temps,https://www.theatre-jeanne.com,Comédie de Léo Pasani. Un spectacle 100 % hum...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Théâtre - Humour"
2,65192,2025-03-12 20:30:00,2025-03-12 23:59:59,20:30,Théâtre de Jeanne,"Récital Barbara, piano/voix - par Mélanie Le C...",https://www.theatre-jeanne.com,Concert/Spectacle musical interprété par Mélan...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Concert - Musique"
3,65194,2025-03-28 20:30:00,2025-03-28 23:59:59,20:30,Théâtre de Jeanne,Vacances obligatoires,https://www.theatre-jeanne.com,Comédie écrite et mise en scène par Bruno Bach...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Théâtre - Humour"
4,65194,2025-03-20 20:30:00,2025-03-20 23:59:59,20:30,Théâtre de Jeanne,Vacances obligatoires,https://www.theatre-jeanne.com,Comédie écrite et mise en scène par Bruno Bach...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Théâtre - Humour"

In [38]:
df['CreatedAt'] = datetime.now()
df['UpdatedAt'] = datetime.now()

In [39]:
df.head()

,id,DateDebut,DateFin,Heure de début,Lieu,Nom,Lien Internet,Description,Image,Adresse,Tarif,Tags,CreatedAt,UpdatedAt
0,65115,2025-02-19 14:30:00,2025-02-19 23:59:59,14:30,Théâtre 100 Noms,Le Bossu de Notre-Dame - par le Théâtre 100 Noms,https://theatre100noms.com/,Création Théâtre 100 NomsUn spectacle enchante...,https://metropole.nantes.fr//banque/public/ima...,21 Quai des Antilles - Hangar à Bananes 44200 ...,PAYANT,"Culture, Concert - Musique, Théâtre - Humour",2025-03-13 12:21:13.252204,2025-03-13 12:21:13.252827
1,65184,2025-03-01 20:30:00,2025-03-01 23:59:59,20:30,Théâtre de Jeanne,Amants à mi-temps,https://www.theatre-jeanne.com,Comédie de Léo Pasani. Un spectacle 100 % hum...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Théâtre - Humour",2025-03-13 12:21:13.252204,2025-03-13 12:21:13.252827
2,65192,2025-03-12 20:30:00,2025-03-12 23:59:59,20:30,Théâtre de Jeanne,"Récital Barbara, piano/voix - par Mélanie Le C...",https://www.theatre-jeanne.com,Concert/Spectacle musical interprété par Mélan...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Concert - Musique",2025-03-13 12:21:13.252204,2025-03-13 12:21:13.252827
3,65194,2025-03-28 20:30:00,2025-03-28 23:59:59,20:30,Théâtre de Jeanne,Vacances obligatoires,https://www.theatre-jeanne.com,Comédie écrite et mise en scène par Bruno Bach...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Théâtre - Humour",2025-03-13 12:21:13.252204,2025-03-13 12:21:13.252827
4,65194,2025-03-20 20:30:00,2025-03-20 23:59:59,20:30,Théâtre de Jeanne,Vacances obligatoires,https://www.theatre-jeanne.com,Comédie écrite et mise en scène par Bruno Bach...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Théâtre - Humour",2025-03-13 12:21:13.252204,2025-03-13 12:21:13.252827

In [40]:
df['id'] = ''
df['IdCreateur'] = ''

In [41]:
df.head()

,id,DateDebut,DateFin,Heure de début,Lieu,Nom,Lien Internet,Description,Image,Adresse,Tarif,Tags,CreatedAt,UpdatedAt,IdCreateur
0,,2025-02-19 14:30:00,2025-02-19 23:59:59,14:30,Théâtre 100 Noms,Le Bossu de Notre-Dame - par le Théâtre 100 Noms,https://theatre100noms.com/,Création Théâtre 100 NomsUn spectacle enchante...,https://metropole.nantes.fr//banque/public/ima...,21 Quai des Antilles - Hangar à Bananes 44200 ...,PAYANT,"Culture, Concert - Musique, Théâtre - Humour",2025-03-13 12:21:13.252204,2025-03-13 12:21:13.252827,
1,,2025-03-01 20:30:00,2025-03-01 23:59:59,20:30,Théâtre de Jeanne,Amants à mi-temps,https://www.theatre-jeanne.com,Comédie de Léo Pasani. Un spectacle 100 % hum...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Théâtre - Humour",2025-03-13 12:21:13.252204,2025-03-13 12:21:13.252827,
2,,2025-03-12 20:30:00,2025-03-12 23:59:59,20:30,Théâtre de Jeanne,"Récital Barbara, piano/voix - par Mélanie Le C...",https://www.theatre-jeanne.com,Concert/Spectacle musical interprété par Mélan...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Concert - Musique",2025-03-13 12:21:13.252204,2025-03-13 12:21:13.252827,
3,,2025-03-28 20:30:00,2025-03-28 23:59:59,20:30,Théâtre de Jeanne,Vacances obligatoires,https://www.theatre-jeanne.com,Comédie écrite et mise en scène par Bruno Bach...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Théâtre - Humour",2025-03-13 12:21:13.252204,2025-03-13 12:21:13.252827,
4,,2025-03-20 20:30:00,2025-03-20 23:59:59,20:30,Théâtre de Jeanne,Vacances obligatoires,https://www.theatre-jeanne.com,Comédie écrite et mise en scène par Bruno Bach...,https://metropole.nantes.fr//banque/public/ima...,5 Rue des Salorges 44100 Nantes,PAYANT,"Culture, Théâtre - Humour",2025-03-13 12:21:13.252204,2025-03-13 12:21:13.252827,

In [42]:
df.drop(columns=['Lien Internet','Heure de début'], inplace = True)

In [ ]:
#df.to_csv('/OUTPUT/nantes_event.csv', index = False)